import React from 'react';
import Head from 'next/head'
import "bootstrap/dist/css/bootstrap.min.css";
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Box from '@mui/material/Box';
import TabPanel from '@/abstractComponents/TabPanel';
import _feed from './Sections/_feed';
import _proveedores from './Sections/_proveedores';

const fetcher = (url: string) => fetch(url).then((res) => res.json())
function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

export default function Home() {
  // const { data, error, isLoading } = useSWR<any>('/api/CRUD/'+`test`, fetcher);
  const [value, setValue] = React.useState(0);
  useEffect(()=>{
    // fetch('/api/userEP', {
    //   method: 'POST',
    //   headers: {
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({name: 'test', age: 9, height: 130}),
    // }).then(status=> {/*console.log(status)*/})
    

    // fetch('/api/userEP', {
    //   method: 'GET',
    //   headers: {
    //     'Content-Type': 'application/json',
    //   }
    // }).then(async response=>{
    //   const data = await response.json();
    //   console.log(data);
    // })

    // fetch('/api/userEP', {
    //   method: 'DELETE',
    //   headers: {
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({name: 'test'}),
    // }).then(status=> {/*console.log(status)*/}) 

    
    // const random = Math.floor(Math.random() * 1000);
    // const user = {_id:'63e56e9400508f74c56a6cd6',name: 'John', age: 8, height: 10};
    // fetch('/api/userEP', {
    //     method: 'PUT',
    //     headers: {
    //       'Content-Type': 'application/json',
    //       'values': JSON.stringify(user._id),
    //     },
    //     body: JSON.stringify({name: 'John', age: random/10, height: random}),
    //   }).then(status=> {/*console.log(status)*/})

  })

  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };


  return (
    <>
      <Head>
        <title>Noticias Hoy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <span style={{display:'flex'}}>
          <img src="./RssIcon.png" alt="" width={'30px'} height={'30px'} />
          <p style={{marginTop:'5px', fontFamily:'Roboto,Helvetica,Arial,sans-serif'}}>¡Entérate!</p>
        </span>
        <Box sx={{ width: '100%' }}>
          <Box sx={{ borderBottom: 1, borderColor: 'divider',width:'90vw' }}>
            <Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
              <Tab label="Feed" {...a11yProps(0)} />
              <Tab label="Proveedores" {...a11yProps(1)} />
            </Tabs>
          </Box>
          <TabPanel value={value} index={0} >
            {_feed()}
          </TabPanel>
          <TabPanel value={value} index={1}>
            {_proveedores()}
          </TabPanel>
        </Box>
      </main>
    </>
  )
}
