import React from 'react';
import Head from 'next/head'
import "bootstrap/dist/css/bootstrap.min.css";
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Box from '@mui/material/Box';
import TabPanel from '@/abstractComponents/TabPanel';
import _feed from './Sections/_feed';
import _proveedores from './Sections/_proveedores';

const fetcher = (url: string) => fetch(url).then((res) => res.json())
function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

export default function Home() {
  // const { data, error, isLoading } = useSWR<any>('/api/CRUD/'+`test`, fetcher);
  const [value, setValue] = React.useState(0);
  useEffect(()=>{
    // fetch('/api/CRUD/1', {
    //   method: 'POST',
    //   headers: {
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({name: 'test', CRUD: 'test'}),
    // })

  })

  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <span style={{display:'flex'}}>
          <img src="./RssIcon.png" alt="" width={'30px'} height={'30px'} />
          <p style={{marginTop:'5px', fontFamily:'Roboto,Helvetica,Arial,sans-serif'}}>¡Entérate!</p>
        </span>
        <Box sx={{ width: '100%' }}>
          <Box sx={{ borderBottom: 1, borderColor: 'divider',width:'90vw' }}>
            <Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
              <Tab label="Feed" {...a11yProps(0)} />
              <Tab label="Proveedores" {...a11yProps(1)} />
            </Tabs>
          </Box>
          <TabPanel value={value} index={0} >
            {_feed()}
          </TabPanel>
          <TabPanel value={value} index={1}>
            {_proveedores()}
          </TabPanel>
        </Box>
      </main>
    </>
  )
}
