import Head from 'next/head'
import asyncCall from 'public/script/rss-parser'
export default function Home() {
  
  return (
    <>
      <Head>
        <title>New PWA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div style={{width:'95vw'}}>
          <h1 style={{textAlign:'center'}} >
            Landing Page!
            
          </h1>
          <button onClick={asyncCall}>
            Activate Lasers
        </button>
        </div>
      </main>
    </>
  )
}